### ISSUE TITLE
Create a mode that doesn't let the user edit the map

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-draw#109]
Would be nice to have support for objects which can't be edited once added (either just by disabling click editing or disabling future `.update` calls).

Boolean could be set either on the GeoJSON properties or passed directly to `.set`.

I started a quick & dirty version at https://github.com/drewbo/gl-draw/tree/permanent for my own purposes but can work on it further (docs + tests) if this is a desired feature.

**Comment by kelvinabrokwa** [comment]
@drewbo the approach you are currently taking will probably do (https://github.com/drewbo/gl-draw/commit/b3863249528efac79870208799cfe2be17ea855a). You can go ahead and issue a PR if it works :) I think this is a useful feature.

**Comment by mcwhittemore** [comment]
@drewbo - why don't you just remove this feature from gl-draw and add it to the map on its own data source?

**Comment by drewbo** [comment]
For my specific project it was nice to leave a feature in the gl-draw "area" so that it could be handled in the same way as user drawn polygons. I touched on this a little in #157

**Comment by mcwhittemore** [comment]
@drewbo the move I think about this the move I think its not the right thing for draw. If you greatly disagree we should rework how permanent features are added to the map so that feature interaction code doesn't have to remember to check for `feature.permanent`.

Short term I'm going to update the docs to indicate that these can't be selected with the api `Draw.select` either.

> Currently the only used option is permanent, which, if set to true, will cause the element to ignore click events which would normally trigger selection.

will become

> Currently the only used option is permanent, which, if set to true, will cause the element to ignore click events, Draw.select and Draw.selectAll calls.

**Comment by drewbo** [comment]
Don't have strong feelings either way. I think there needs to be some way of making one (or all?) elements non-interactive after they are placed or after some user choice is made (maybe the whole drawing mechanism turns off?) because it seems like a common application pattern (differentiating "drawing mode" from some other form of interaction)

**Comment by mcwhittemore** [comment]
Do you have an unselected, selected, and being edited state?

gl-draw used to have this and we removed it when trying to clear up some internal concepts. Permeant was around at that time so I assumed that different selection modes didn't solve your problem here.

The problem I see with having three states in gl-draw rather than two is how to give power users an api that lets you control going from unselected -> selected -> edit mode without making it too hard for implementors looking for a drop in solution.

The problem I see with gl-draw only having unselected and edit mode is that it requires users who want to add a selected mode to change the filters on layers or add/remove the data from gl-draw and push it to their own source.

A related conversation here is #219. If everything was in one source and we disallowed properties inside of gl-draw... we could make it very clear which source the data would be in and we could create lots of different views by exposing the the values of feature state to the source. Doing this would require people to always ignore the properties coming out of gl-draw on events (we'd likely set it to an empty {} so this was clear).

**Comment by drewbo** [comment]
We have only unselected and being edited states and now that the product is released, I can actually share the use case: https://fetch.astrodigital.com/

We use draw to add the dotted line "filtering area" on the map, regardless of how it is added (it follows the viewport by default and then users can choose to draw or upload their own area). The initial problem was that after it was added, a user click would re-enable draw mode which wasn't the desired behavior.

I think there will be lots of cases (although I'm super biased) where people want to use draw to have the user add something but then enter another mode of the application where editing isn't the default behavior.

**Comment by mcwhittemore** [comment]
In talking this over with @lucaswoj he strongly suggested we keep two sources. One for things that are being changed a lot and one for things that aren't being changed a lot. This is a bit different that the current selected and non-selected model we're using.

**Comment by drewbo** [comment]
I guess as long as the GeoJSON is returned after certain events (`draw.complete` most notably), it could be on the developer to decide where to push the data to in that case.

**Comment by mcwhittemore** [comment]
@drewbo - is your use case on the web somewhere where I can see it?

I think there are a lot more states than just the being-edited and not-being-edited and I think gl-draw needs to handle these.

**Comment by drewbo** [comment]
Very late followup but just as a reference, I implemented this on my fork as a separate mode called `'static'`: https://github.com/drewbo/mapbox-gl-draw/commit/d6cfbb8760e2a8661b9a6eb62af2836319278b01

**Comment by mcwhittemore** [comment]
@drewbo if this is helpful for you, I think I'd be open to the PR. It looks like it would be good for doing simple animations if you use it with the new `Draw.set` function.

**Comment by davidtheclark** [comment]
Done in #435.
