### ISSUE TITLE
Set minimum nodes when delete

### ISSUE THREAD

**Issue by mayagao** [mapbox/mapbox-gl-draw#237]
Right now i'm able to delete all the nodes through double clicking. Need to have 2 minimum nodes for lineString and 3 minimum nodes for polygon.

**Comment by mcwhittemore** [comment]
I think the real problem here is that deleting the feature by deleting nodes breaks the `esc` functionality. Normally `esc` will undo your changes to the feature, but once you have killed it, that is currently not possible.

We can either fix the `esc` functionality to bring back features deleted this way or we can not let people delete features this way.

**Comment by mcwhittemore** [comment]
The direct_select mode in fresh-start handles this by making deleting nodes clearer. Most drawing tools let you delete a feature by deleting the nodes so we are going to keep that.
