### ISSUE TITLE
midpoints are off at zoom level 22

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#256]
![image](https://cloud.githubusercontent.com/assets/1551510/13645849/e4f8cfbc-e5fa-11e5-8f70-3d25af34d08a.png)

**Comment by kelvinabrokwa** [comment]
This is very strange since the midpoints are calculated [using the pixel coordinates][1] (not lon, lat).

This was an issue earlier when they used lon, lat -> https://github.com/mapbox/mapbox-gl-draw/issues/55

Possibly floating point round-off error

[1]: https://github.com/mapbox/mapbox-gl-draw/blob/a2666a564662db817c33cb292b30dea6ffe7375c/src/lib/create_midpoints.js#L16-L18

**Comment by mcwhittemore** [comment]
@kelvinabrokwa yea, I'm guessing this is a rounding error as well as precision is the key difference between each zoom level.

**Comment by kelvinabrokwa** [comment]
Sure

**Comment by averas** [comment]
Could be related to https://github.com/mapbox/mapbox-gl-js/issues/2279

**Comment by mourner** [comment]
I think this happens because of low GeoJSONSource maxzoom. https://github.com/mapbox/mapbox-gl-js/commit/d6c34c81f7b0d6e77f1b25c2c080a3c5afba94ab should have fixed this.

**Comment by mcwhittemore** [comment]
@mourner this is fixed in mapbox-gl@0.16.0. Thanks!
