### ISSUE TITLE
Draw modes should be an ENUM

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-draw#267]
> Would prefer modes to be either enums (Draw.modes.DEFAULT) or separate methods (Draw.startDirectSelect(id), Draw.startDrawing(Draw.types.LINE)) although then I'm not positive what draw.changemode should emit.

> - @drewbo

**Comment by drewbo** [comment]
@mcwhittemore before I start on this in earnest what do you think of the following modes (all called with `.changeMode`:

string | enum
--- | ---
`select.simple` | `Draw.modes.SELECT_SIMPLE`
`select.direct`  | `Draw.modes.SELECT_DIRECT`
`draw.linestring` | `Draw.modes.DRAW_LINE_STRING`
`draw.polygon` | `Draw.modes.DRAW_POLYGON`
`draw.point` | `Draw.modes.DRAW_POINT`

then the internal code can rely on the constants instead of doing string replacement if things change.

Also, is there a ES5 vs ES6 preference for this library? Seems like now it's a little bit of a mix. (e.g. `var {noFeature, isOfMetaType, isShiftDown} = require('../lib/common_selectors');` uses destructuring but not import)

**Comment by mcwhittemore** [comment]
`draw.word` is our notation for events so I'd prefer we use `_` for mode names. The other naming changes are great.

The es6/es5 question is a good one. It was very es6 but classes have some problems and I don't really like the idea of using es6 for modules as it can require people to have babel installed who don't want to use it at all.

That said, I know this isn't the tradition of this module. So I'm open to discussion on it. That said, that should be in another issue.

**Comment by drewbo** [comment]
Cool; I'll ignore ES6vs5 questions for now.

Part personal preference and part convention but I generally don't like underscores in JS, unless it's the library or breaking up a constant name. What about dashes (e.g. `draw-polygon` or `select-simple`)? The only other strings with specified inputs in the mapbox-gl api besides events (all lowercase) are the positions for controls which also use dashes (`top-right`).

**Comment by mcwhittemore** [comment]
Sounds good

**Comment by davidtheclark** [comment]
@mcwhittemore Should we follow through with this as part of our next release?

**Comment by mcwhittemore** [comment]
@davidtheclark +1

**Comment by davidtheclark** [comment]
Am I right in thinking that the plan here is to expose a `Draw.modes` as part of the documented API? Just want to be clear — might take care of it within the next day or two.
