### ISSUE TITLE
.delete() should clear selection

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#357]
Seems like `draw.delete()` should clear the selection every time it's used. That way `draw.trash()` just needs to use `draw.delete()` and not manually deselect features.

Trouble is, the store code, of which `delete` is a part, does not currently have access to the selected features object in `simple_select.js`. So *I propose we stash the object of selected items on the store, instead of leaving it as a variable only available in `simple_select.js`.* 

Does that seem acceptable? I can put together a PR.

cc/ @mcwhittemore @samanpwbb

**Comment by mcwhittemore** [comment]
@davidtheclark each mode maintains what it considers selected. This is because some modes select features and other select vertices. `trash` is implemented by the mode so that that mode can delete what it wants to delete. This is how you are able to delete just a vertex when you are dragging a vertex around.

**Comment by davidtheclark** [comment]
@mcwhittemore Yeah, I think that makes sense to me. To clarify my idea:  My proposal here is to make the delete method always deselect whatever it deletes. Right now trash deletes and then deselects, but delete alone does not deselect, and that's causing Studio bugs.

**Comment by mcwhittemore** [comment]
@davidtheclark yea, tis a good idea. I've love to see a PR that gets at this. I'm not really sure how we should go about it.
