### ISSUE TITLE
The first time you click any feature a draw.modified event is fired

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-draw#393]
And it should not be, since you are not modifying features.

**Comment by davidtheclark** [comment]
I'd like to change the name of this event to `update`, and make it fire when an existing feature has been updated. Here are the times that make sense to me:

- When you finish moving a feature (mouseup). (`draw.change` would fire again and again while you move the feature.)
- When you finish moving a vertex (mouseup or Enter keyup). (`draw.change` would fire again and again while you move the vertex.)
- When you delete a vertex.  (`draw.change` also fires here, I guess.)

Unlike the current `draw.modified` event it would not fire:

- When you create a new vertex while creating the feature (wouldn't fire at all in `draw_*` mode).
- When you select/deselect an element.

As long as we're considering this API, the reason for #391, I think, is because I was bouncing back and forth, unclear about whether our intention is to emit feature ids or the features themselves. Seems like it might be inconsistent at the moment (e.g. https://github.com/mapbox/mapbox-gl-draw/issues/307).

If I were to standardize that, would you prefer features or feature ids to be emitted?

**Comment by mcwhittemore** [comment]
It looks like this happens the first time you click anywhere on the map after a feature has been added.

**Comment by mcwhittemore** [comment]
@davidtheclark lets hit these thing things on this issue

- When you select/deselect an element.
- When you add an element and than click

And than look into getting the `draw_*` modes to not emit this event later.

I also want to talk about renaming this / dropping `draw.changed` at the same time.

**Comment by davidtheclark** [comment]
> hit these thing

You mean remove those firings?

**Comment by mcwhittemore** [comment]
Yea

**Comment by davidtheclark** [comment]
As of #407 there is no `draw.modified`: it's been replaced with `draw.update`, which doesn't have this problem.
