### ISSUE TITLE
Audit one-handler-per-event system

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#459]
I'm a little concerned that there might be some reason to take another look at the move in https://github.com/mapbox/mapbox-gl-draw/pull/453/commits/1d4527b5bf33330771d2a4be167722c52c00359c to enforce only one handler per event.

Maybe there's nothing wrong, but here are my concerns:
1. I'm not sure we're currently using the events in a way that expects this everywhere. For example, I wonder if https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/direct_select.js#L78 is now subtly wrong, because if its handler fires it means the other `mousedown` handlers won't, right? — but they should.
2. Generally I just kind of find this more confusing than the other way, because we are accustomed to `addEventListener` and EventEmitters where you can attach as many handlers as you want, independently. Why rely on order of operations to filter _all_ handlers when you could rely on explicit conditionals to filter those handlers you want to filter?

So because of the first point, I opened this issue because at some point the code should be reviewed to ensure there isn't weirdness around expecting more handlers to be called than will be. (The second point is just my question.)

**Comment by mcwhittemore** [comment]
@davidtheclark I agree its a bit weird at first I tried to replace the `CommonSelectors.true` with `CommonSelectors.noTarget` but that failed. Looking at it now, we might be able to replace `CommonSelectors.true` with `CommonSelectors.notVertex` or something like that.

A bit of history here, events have only been able to be handled once per mode since 390585ae307b8cb29e13aaa1c762534cf7566624. I missed you're removal of the break in ae730111a9965342401d873369106f3871eb188e when I reviewed it, so I was concerned there were more places where two events were firing. Did you do check that more handlers weren't being fired when you removed the break?

I think the best approach would be to drop the selector filter from mode_handler and have normal event handlers per mode. The common selectors can still be used, but they will be used in if statements in the event handler not before the event handler.

**Comment by davidtheclark** [comment]
> I think the best approach would be to drop the selector filter from mode_handler and have normal event handlers per mode. The common selectors can still be used, but they will be used in if statements in the event handler not before the event handler.

That sounds like a good approach to me. The closer we get to the common event handler behavior, the better.

**Comment by mcwhittemore** [comment]
There is an extra handler in `direct_select` that needs to be deleted.

https://github.com/mapbox/mapbox-gl-draw/blob/696a2078143ac2ea314698b1351c354236be7365/src/modes/direct_select.js#L141

**Comment by mcwhittemore** [comment]
Custom modes now forces this to be true
