### ISSUE TITLE
mapboxgl.Popup() can't work in draw envent

### ISSUE THREAD

**Issue by wanyanyan** [mapbox/mapbox-gl-draw#495]
I want to show a popup when `draw.create` , it can't work in the event callback, and no error in console. But it works well in `click` evnet. How did it happen? 
This is my test code:
```
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.22.0/mapbox-gl.js'></script>
	<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.22.0/mapbox-gl.css' rel='stylesheet' />
	<script src='mapbox-gl-draw.js'></script>
	<link href='mapbox-gl-draw.css' rel='stylesheet'/>

<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoid2FueWFueWFuIiwiYSI6Im1uNVZnTncifQ.90XY40_yjpItUHO8HnbbpA';
var map = new mapboxgl.Map({
	container: 'map',
	center: [116.420679, 37.772537],
	zoom: 8,
	style: 'mapbox://styles/mapbox/satellite-v9',
	hash: true
});
window.Draw = mapboxgl.Draw();
map.addControl(Draw);
map.on("draw.create",function(e){
var popup = new mapboxgl.Popup()
  .setLngLat([116,40])
  .setHTML("<h1>Hello World!</h1>")
  .addTo(map);
</script>
```

**Comment by mcwhittemore** [comment]
@wanyanyan - sorry I missed this. I'm not sure why this is happening. I'll look into it today.

**Comment by mcwhittemore** [comment]
@wanyanyan - The problem here is that the mouse event that triggers the `draw.created` event, also closes the popup. What you need to do is stop that event from running. Sadly you can't do that here. @lucaswoj and I were talking about events earlier today. I think this is still something mapbox-gl-js and its extension need to work out.

A quick hack would be to use `setTimeout` to put your action into the future... :(

**Comment by wanyanyan** [comment]
Thank you for your answer, I will try agin.
