### ISSUE TITLE
Add and split interior rings to/from polygons

### ISSUE THREAD

**Issue by ghoshkaj** [mapbox/mapbox-gl-draw#518]
Following on from https://github.com/mapbox/mapbox-gl-draw/issues/355 we want to be able to add interior rings to a polygon and split interior rings from polygons:

![screen shot 2016-10-12 at 10 58 14 am](https://cloud.githubusercontent.com/assets/6777404/19315540/15432c32-906c-11e6-9c3e-e47ceef0d4a6.png)

**Comment by mcwhittemore** [comment]
This is a great idea, and I'd really like to see this in v2 of MapboxDraw, but for now it should be done as a [custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw)

**Comment by katfchan** [comment]
Is there any progress/update on this ticket? Or any tips as to how to make this a mode? I have something something that depends on this and creating my own mode doesn't seem super straight forward, at least to me. 

I think it could be something similar to `combineFeatures`, where the user selects the 2 or more polygons, press some interior rings button, which then turns the polygons into one (same applies when removing inner rings and `uncombineFeatures`). I've tried to make it into a custom mode, but it doesn't quite make sense to me to do so since it's just one action at the click of a button. I've also tried to manually do it without a custom mode, but there are a lot of functions that I'd like to use that only seem to be available within a custom mode.

**Comment by mcwhittemore** [comment]
@katfchan - there are no plans to my knowledge to work on this. A simple (but likely not perfect) way to do this would be to have a custom button in your app that is displayed when two or more polygons are selected in draw and on clicking that button you would:

1) merge the coordinate arrays on the polygons into a new feature
2) delete the selected polygons
3) add the new polygon to the map
4) select the new polygon

[Here is a link to the api docs](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md) where you can find the draw functions to do everything in that list except the merge.

There are problems with this such as not enforcing winding order or having inner rings overlap with outer rings, but once you have a naive implementation you can likely start solving some of these more complex problems. Off the top of my head, I can't remember what the GeoJSON spec requires here or if MapboxGL is stricter about any of these rules.

**Comment by katfchan** [comment]
@mcwhittemore that helps a lot. Thanks so much!
