### ISSUE TITLE
Consider forcing longitudes into the real world

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-draw#535]
Right now you can draw features with longitudes >180 and <-180. By doing so, you can create GeoJSON that breaks other tools. Even the rendering mapbox-gl-js will break at a certain point (beyond +-540); but +-180 itself is an important limit for plenty of other geospatial tools.

I've been working on a module, [stacker-of-worlds](https://github.com/mapbox/stacker-of-worlds), to transform features with out-of-bounds longitudes into MultiFeatures that are contained within the real world. Now that Draw supports MultiFeatures, maybe it's worth an experiment incorporating this functionality into Draw.

The goal would be that *as you draw*, if you create points outside longitudes +-180, they are automatically transformed.

Benefits:

- Compatibility with mapbox-gl-js without having to impose panning restrictions.
- Compatibility with other geospatial tools.
- Created Features would abide by [the suggestion in the GeoJSON spec](https://tools.ietf.org/html/rfc7946#section-3.1.9) for Features that cross the antimeridian.

Anticipated downsides:

- Your feature would end up with a line at the antimeridian.

**Comment by mcwhittemore** [comment]
I've been thinking about this a bunch over the last few days.

There are two problems facing this.

1. It's really hard to slice polygons.
2. There is currently no way to style two polygons to look like one if we have a border. There will always be a line running down the split.

The first problem would need to be solved by [stacker-of-worlds](https://github.com/mapbox/stacker-of-worlds).

The second problem can be solved in one of three ways.

1. We could use the +/-540 line to trim the extra borders off of the shape. This would require `stacker-of-worlds` to accept a +/- 540 world.
2. We could use line_strings to represent borders rather than the current option
3. We could update the style spec to somehow solve this...

I'm going to assume that option 3 is a reach.

Option one seems the easiest. Since we need stacker-of-worlds to work for this to even be a thought, saying that `stacker-of-worlds` needs to accept a definition of the boundary of a world as part of its config doesn't seem like too much to ask for.

Option two would be a breaking change to how Draw maps are styled. While this doesn't make this a no-go option, I think this should only be considered if option one is impossible.

@davidtheclark / @tmcw, how realistic is `stacker-of-worlds`? I know that this requires splitting polygons which is a continual problem for us. Are we at a point where we just need to solve this problem? @tmcw, who were you offering 🍪s to to solve this again?

**Comment by davidtheclark** [comment]
> It's really hard to slice polygons.

stacker-of-worlds this is done with `turf.intersect` — so the result will be as accurate as `turf.intersect` is. If `node-gdal` or something else has better accuracy we can try those. After experiment with `node-gdal`, mapnik, and turn, I was able to get the best *visually confirmed* results (i.e. looking at gl-js maps rendering GeoJSON sources) with the current method: project the feature and a "world" rectangle; find the intersection with turf; unproject the intersection.

A big open question I have about that experiment is https://github.com/mapbox/stacker-of-worlds/issues/2: visual comparison being less-than-ideal, how can we verify the accuracy of the output?

> I know that this requires splitting polygons which is a continual problem for us.

Is there some sample Tricky Polygon I can try out in stacker-of-worlds to see how it works?

> There is currently no way to style two polygons to look like one if we have a border. There will always be a line running down the split.

I agree that this is annoying, but I'm not sure I think this should stand in the way. Because world-spanning features with lines at the antimeridian are better than *no* world-spanning features, which is the other option.

> This would require stacker-of-worlds to accept a +/- 540 world.

I'm afraid this would spoil of the main goals of stacker-of-worlds, though, which is to output GeoJSON that is compatible with the full unpacker pipeline (and other geospatial tools), which means it has to be contained to +/- 180.

**Comment by mcwhittemore** [comment]
> I'm afraid this would spoil one of the main goals of stacker-of-worlds

Can't `stacker-of-worlds` be written to let the edge of the world be customizable?

**Comment by mcwhittemore** [comment]
> Is there some sample Tricky Polygon I can try out in stacker-of-worlds to see how it works?

A polygon where the inner ring touches the outer ring is I think a simple example of something that will break turf. @tmcw might have a better example.

**Comment by davidtheclark** [comment]
> Can't stacker-of-worlds be written to let the edge of the world be customizable?

It can, but then we're not fixing the problem that this is all aimed at fixing — that's what I mean. +/-540 is meaningless to every tool except mapbox-gl-js, right? I'm under the impression we need to hit +/-180 in order to make Draw's output widely compatible.

**Comment by mcwhittemore** [comment]
@davidtheclark - I'm thinking about how we send data `mapbox-gl-js`. 

Transforming the output is another option, but I don't think it's wise to break a polygon into a multi_polygon because it crosses the 180. Changing the type of feature the user is creating is unexpected to them and would result in actions like combine and uncombine breaking features apart that the end-user didn't expect to be splittable.

There is the argument that we could only stacker of worlds on export. But then reimporting that data would have the same confusing results. I think keeping stacker-of-worlds as a tool just before the geojson is sent to a tool that only support a finate number of worlds (be it 1, 3, or 50).

**Comment by davidtheclark** [comment]
@mcwhittemore Yeah — I'm afraid, though, that we won't be able to avoid stacking features *at some point*, and I wonder if it's therefore best to do it consistently across tools. 

Let's say a user draws otherworldly features in the dataset editor, and we allow that to be saved to a dataset without stacking. Everything looks fine, no antimeridian lines or unexpected MultiFeatures; so they try to export that data to a tileset. Currently, the export will just not work, and that's not really acceptable. In order for the export to work, we're going to have to stack to +/-180. Then the user will look at their tileset rendered in the style editor, and see a line at the antimeridian that does not exist in the dataset editor. That would be confusing.

Also: If Draw were to split features at +/-540 instead of +/-180 to avoid breaking mapbox-gl-js — some users will still face the same auto-stacking at some point, it will just be *more* confusing when it does happen because it will not be *consistent*.

**Comment by davidtheclark** [comment]
Another possibility is that we could leave Draw itself out of this and just impose stacking within Studio's dataset editor. Because of the two problems here — mapbox-gl-js breaks outside +/-540, other tools break outside +/-180 — other users of Draw might not face the other-tools-breaking problem. But in Studio's dataset editor we don't really have a choice except to either stack features or, as we're currently doing, disallow panning across the antimeridian and thereby making it impossible to draw Features that cross it.

**Comment by mcwhittemore** [comment]
There are three types of GeoJSON we can split.

1. We can split the GeoJSON the user gets from Draw. This will be exported to other tools and splitting here would help interoperability at the cost of unexpected changes.
2. We can split the GeoJSON that draw stores. This would happen as the user draws or adds data. By doing the split here, we'd achieve number 1 and also achieve number 3 but it would result in the types of features changing as the user worked with the data and could lead to unexpected behaviors.
3. We can split the GeoJSON that draw sends to `mapbox-gl-js`. This would have no effect on the data the user gets or store users show the functionality of Draw and the export of the data would not be affected. Styling get a bit more difficult, mostly for the reason I mentioned in my first comment.

Does that sound right @davidtheclark?

Personally, I think number 3 is the only desirable option. Data should stay as close to what the user provides as possible. While features created by Draw could follow some rule that splits them at 180, transforming external GeoJSON creates a lot of problems and we'd need to do that transform for both option 1 and 2.

**Comment by davidtheclark** [comment]
> I think number 3 is the only desirable option

But 3 doesn't solve the tool-compatibility we have that can't be avoided in Studio. Are you suggesting we solve it in *only for* Studio, within Studio, and leave Draw out of it?

**Comment by davidtheclark** [comment]
As discussed in chat: let's leave the stacking of features to other tools, and for now just warn users of Draw that they should probably limit their gl-js maps to +/-540 longitudes to avoid rendering problems.

**Comment by mcwhittemore** [comment]
Reopening this as it is still a problem and should be open until we decide to `wont-fix` it or ship a solution.

**Comment by mcwhittemore** [comment]
This is now a `wont-fix`, though I'd love to see a [custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw) that does this.

**Comment by cjerv** [comment]
What is the fix?

There are apps using mapbox that are able to cross the dateline, just wondering what is the fix?
![IMG_517A382404F1-1](https://user-images.githubusercontent.com/93710516/183244551-28e962f4-0dad-43e7-871a-ec7447fccc15.jpeg)
