### ISSUE TITLE
snap to vertex and edge of other features

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-draw#557]
Feature request to include an editing mode which snaps to vertices and edges from other point/line/polygon features when the cursor is within a small buffer.

**Comment by mcwhittemore** [comment]
@andrewharvey - This is a great idea. Do you want to take a stab at making it happen? I think getting it to work in the `draw_line_string` and the `draw_polygon` modes would be a good first step. Once it works well there thinking about how to get it to work in `direct_select` can happen.

**Comment by BellisJ** [comment]
I'm beginning to work on this on my end as well. I was just going to attempt to tackle it as a hack; but  I will begin looking into contributing what I can. This is definitely some solid functionality to have for most peoples drawing and dragging needs.

**Comment by andrewharvey** [comment]
> @andrewharvey - This is a great idea. Do you want to take a stab at making it happen?

I probably won't get around to this soon, @BellisJ it will be good to see what you come up with.

**Comment by ravraponi** [comment]
@BellisJ How is this going?  I need this functionality as well - do you need any help?

**Comment by BellisJ** [comment]
@ravraponi I've gotten a bit delayed with this due to some other projects taking over my work life for the time being. But I can definitely use some assistance with this stuff. I probably won't be getting back to this till next year at work nor in my freetime though. But if you decide to dive in, I'll make it a point to try to contribute more.

I've started looking at draw_line_string, draw_polygon, and draw_point based on mcwhittemore suggestions above, but I did not really get that far. Editing this into mapbox-gl-draw is looking to be quite involved and maybe a bit over my head. I still need to become more familiar with the mapbox-gl-draw source code before I can start really contributing on this.

When I was looking at this as a hack, I was just using turf.js to calculate nearest vertexes from selected features vertexes then "snap" based on a distance search. But I was getting some bad performance on my first real attempt with this logic. I know we can't rely on turf when editing the actual mapbox-gl-draw code, but its a good way to simplify prototypes and explore logic for snapping. While exploring snapping on this front I did realize we have three variations of snapping; vertex to vertex snapping, vertex to edge, and edge to edge. That should cover all types of snapping I can think off, and probably the easiest to go after first will be vertex to vertex.

**Comment by mcwhittemore** [comment]
@BellisJ - thanks for taking the time to think this through and try a prototype. Performance is definitely a concern we need to keep in mind.

Aiming for vertex-to-vertex snapping as the first pass is a great idea. We'd want to create some sort of index of all the vertices in other features at the start of the draw mode so that we only do this once.

I too don't have time to work on this right now, but if someone wants to POC out this indexing I can help contribute ideas to how to make it efficient.

**Comment by ravraponi** [comment]
@mcwhittemore  - I hope to have some time to work on this by starting with the vertex to vertex snapping.  Any ideas to be more efficient would be helpful.

**Comment by mcwhittemore** [comment]
@ravraponi - yea, so my first stab would be to create a way to encode the lng/lat into a string so that all lng/lats in x distance will colloid in the string space.

As a bit of completely untested code, I'd try something like this:

```js
function lngLatToKey(lng, lat, dist) {
  var smallLng = (lng/dist).toFixed(6);
  var smallLat = (lat/dist).toFixed(6);
  return smallLng+'-'+smallLat;
}
```

My concern with the above code would be if the decimals are being cleaned up enough to keep everything in once string space.

Once you have this you'd loop through all of the vertices and create an object that looks something like:

```js
{
  "0.0": [ [0,0], [1,1], [2,2]]
}
```

Now if the position you are moving matches the "0.0" lngLatString you know its close to one of the lngLats in the array and you can do a dist sort to find which one is closest to your point.

**Comment by jmking** [comment]
This is a feature I'm very keen on as well. I hope to have a go at it if I can find the time. In the long term what I would love is if ultimately we can enable:
- snapping to vertex
- snapping to a point along a linestring
- Some kind of data driven snapping (i.e. feature with attribute A can snap to features with attribute B or C).

**Comment by mcwhittemore** [comment]
MapboxDraw's functionality is locked for v1, this should be done as a [custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw)

**Comment by donnyv** [comment]
Is there anyway to use this besides building a custom version of mapbox-gl-js?

**Comment by ravraponi** [comment]
Only a custom version of mapbox-gl-draw.
The old snap pull was:
https://github.com/mapbox/mapbox-gl-draw/pull/583

**Comment by canadaka** [comment]
No one has created a custom mode for snapping yet? 
This was well over a year ago.

**Comment by jmking** [comment]
We created one which is used at the company I work at. I'll look into getting it open sourced.

**Comment by tomasdev** [comment]
@jmking any news? or anyone in the thread?

**Comment by donnyv** [comment]
Found this, which is a good start.
https://stackoverflow.com/questions/51931925/snapping-a-draggable-point-to-a-vector-tile-set-line-in-mapbox-gl-js-using-turf?rq=1
