### ISSUE TITLE
Options to prevent polygon self-intersections

### ISSUE THREAD

**Issue by FlorianBurgevin** [mapbox/mapbox-gl-draw#573]
Hello,

Is there an option to prevent self-intersected polygons when I'm drawing one?

Example:
![image](https://cloud.githubusercontent.com/assets/6703118/21563512/71291642-ce83-11e6-9a2e-b86f42e3a79b.png)

In leaflet draw there is these options and it's impossible to validate the next point

> allowIntersection: false,
> showArea: true,
> drawError: {
>     color: '#e1e100',
>     timeout: 1000,
>     message: '<strong>Oh snap!<strong> you can\'t draw that!'
> }

How can I do that with MapboxGL? 

Thank you

**Comment by mcwhittemore** [comment]
@FlorianBurgevin - while this is an invalid polygon according to mapbox-gl it is a valid polygon according to geojosn. Since Draw is a geojson editor for mapbox-gl, we have decided that it will support the geojson spec. Not doing this would get us into some interesting cases where a user uploads a geojson file and cannot edit it.

That said, you can handle this yourself, by tracking history and validating the polygon via the [draw.create](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#drawcreate] and [draw.update](https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#drawupdate) events.
