### ISSUE TITLE
Enforce simple polygons

### ISSUE THREAD

**Issue by ravraponi** [mapbox/mapbox-gl-draw#584]
Feature request to prevent self intersection on polygons/lines.
Add a new boolean option, say "allowSelfIntersection" which when false would prevent a new point from being added if it self-intersecects on ploygons/lines.

**Comment by davidtheclark** [comment]
Let's experiment with enforcing simple polygons. This would open up possibilities for addressing our multi-world-longitudes problems, because it would allow for accurate intersection calculations.

We'd need to disable (with a disabled style and everything) any non-simple polygons that a user manually loads into Draw's data.

Here are the immediate problems: 
- How can we determine whether a polygon is a simple polygon? 
- What is the best UI behavior for blocking a user from trying to do things that cannot be done? We could just prevent the creation of vertexes that would un-simplify the polygon. Maybe we should change the cursor to indicate that a click here won't work.

cc @mcwhittemore 

@ravraponi I don't think we're interested in blocking self-intersecting lines. You could listen for events and enforce your own validation for this. I changed the title of this issue accordingly.

**Comment by ravraponi** [comment]
We have been having problems with intersecting lines in polygons leaving line artifacts at different zoom levels.  If enforcing simple polygons prevents this happening then it sounds good.

  I would love to know how to determine whether a polygon is a simple polygon.

**Comment by mcwhittemore** [comment]
I'd like to see this as a [custom mode](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/README.md#creating-modes-for-mapbox-draw). I doubt we'd add this to Draw ever as Draw should support all valid GeoJSON, but I know there are users who'd like this.
