### ISSUE TITLE
Improve drawing support for Polygon and LineString in touch environments

### ISSUE THREAD

**Issue by FlorianBurgevin** [mapbox/mapbox-gl-draw#610]
Hello,

I'm not able to find how to display all the polygon points when i'm drawing one. Only the vertex points are visible.

Does the feature is available?

**Comment by mcwhittemore** [comment]
In the drawing modes, only the first and last points are shown. This is to help cut down on the number of the things we are updating while drawing. Since this is when users see the most change, we want to make sure it is as performant as possible.

**Comment by FlorianBurgevin** [comment]
Ok I understand thanks.

So the issue is the first clicked point and the second are not displayed. Vertex starts at the third point?

**Comment by mcwhittemore** [comment]
The vertices aren't shown until the Polygon is valid (which is after the third click). Once the third click happens, there should be a dot on the first the last place you clicked. These dots can be clicked to finish drawing the polygon.

**Comment by FlorianBurgevin** [comment]
Yes that's it.

Is there any way to show the first two points during the drawing?

My problem is that on mobile, it's hard to understand after first click because nothing happened.
That's why I want to show first and second point before the third point is clicked. This is good after the third point is clicked.

**Comment by mcwhittemore** [comment]
ah... mobile... that would be a problem.

@FlorianBurgevin I'm more than willing to rethink this a bit. Would you be up to running out the PR?

@ChrisBellew did the work on getting touch support added in, so we might want to bring him into this convo as well.

**Comment by FlorianBurgevin** [comment]
I can have a look at the code. But maybe it could be interesting to talk about the good behavior.

Is that always to draw first two points? Or at least an option to style them like the vertices.

**Comment by mcwhittemore** [comment]
> maybe it could be interesting to talk about the good behavior.

I agree we should talk about what we want here before diving in. I just also want to make sure that someone in the convo has the time and will to do this. A good convo will no follow up won't solve our problem.

> Is that always to draw first two points? Or at least an option to style them like the vertices.

So, I think we need to think about this in the context of `touch` and in the context of `mouse`.

What we have right now works pretty well for `mouse`. We should the line as you are drawing and turn this into polygon when there are enough Positions added to the shape. Once we can show a polygon, we also start to show the `start` and `end` positions in the polygon to help users end drawing by clicking on either the `start` or `end`.

Now, in a touch environment, this doesn't work well because there is no event being fired as the user moves their hand to the next location they are going to touch. Without this `moving` events we are unable to draw the line that lets the user know drawing has begun.

@FlorianBurgevin, if I understand correctly, is suggesting that in the `touch` environment we show the position on the first touch. This will let users know their tap resulted in drawing starting. This makes sense to me. On the second tap, do we then show two Positions with a line connecting them? Again, I think this makes sense. On the third tap, we'd be in the state where `click` environments start to show positions and I think we'd want to use the same display logic.

Thinking this over, I'm not sure why we wouldn't want to show the same logic for `click` and `touch` if we follow the above `touch` idea.

Anyway, that is my thought about how to do this. I've done very little with mobile, so I'm not sure if this is really a good idea. I'd love some input from people who use (or are looking to use) Draw for mobile.

**Comment by FlorianBurgevin** [comment]
I followed your logic and I totally agree with it !

I think what really important for the mobile user (and finally for all users) is the `feedback` gave when you click.
Currently, this feedback is at the beggining only when your mouse move. If the user do not move his mouse, we have the same problem.

So, the idea that the logic is the same for `click` and `touch` is good.

The following image is a good example for a good feedback when the user is drawing.

![how-to-draw](https://cloud.githubusercontent.com/assets/6703118/23942916/0aac5872-096e-11e7-83b7-5102669fb8bc.gif)

Combining this with the current behaviour can be an intersting thing.

So the logic can be:
    - First point clicked: drawing the point
    - Second point clicked: both points and linestring drawn
    - Third point clicked: same as current version with first and last points visible

Thinking on that, why not go further and allow to display all points if we want? There is `meta` for vertices. Maybe we can have an other `meta` that allow to style all points. By default, we keep the current logic with only vertices visible, but with filters combination, allow to show all points?

If we want to go further again, the gif above provide an other `cursor` (a target) instead of the default pointer. This can increase again the comprehension of the user.

**Comment by FlorianBurgevin** [comment]
Do you have some news on this subject?

**Comment by mcwhittemore** [comment]
@FlorianBurgevin - I think there are a lot of good here. I'm pretty busy right now, but I can spirit guide a PR if you want to contribute. Sorry for the slow reply.

**Comment by z0d14c** [comment]
I'd like to add that it is currently very difficult in our app to finish polygons or polylines, the touch doesn't seem to register on the first/last/any vertex to finish the shape. Adjusting touchBuffer doesn't seem to help. Any advice would be appreciated, otherwise I will try to dig into the problem deeper and see if there is a contribution to be made.

**Comment by z0d14c** [comment]
addendum to the previous comment... our difficulties seem to occur when using custom styles to make the vertices more visible. unfortunately they are now near impossible to tap to finish the shape despite being made larger.

**Comment by mcwhittemore** [comment]
@z0d14c - have you tried changing the `touchBuffer`?

https://github.com/mapbox/mapbox-gl-draw/blob/master/API.md#options

**Comment by z0d14c** [comment]
@mcwhittemore yeah thats not a problem any more, but yeah we really need better "visuals" for mobile users -- not seeing the first node they draw is super not bueno. 

i can get started at this probably some time in the next few days, do you have any tips or guidance into how this might be properly implemented?

**Comment by mcwhittemore** [comment]
@z0d14c - So, understanding how the `render` function works for each mode is a bit tricky. The idea is that a feature comes in and the function pushes any number of features out. What gets pushed is what gets rendered. This lets us render a bunch of points and a polygon for a single polygon and it lets us render a point than line_string rather than a polygon when the polygon isn't a polygon yet.

Because Draw was written with mouse interactions in mind, some of the if statements that lead to pushing features to the renderer don't get triggered unless the mouse has moved.

I hope we can fix this just in the render function, but we might need to expand into the event handlers as well.

**Comment by CookieCookson** [comment]
I'm having the same issues here with insufficient mobile support. It is really confusing my users as to whether the first 'touch' has happened or not. From my experience it needs to:

1. Display the first 'point' on first touch
2. Add the second 'point' on second touch and draw the line connecting them
3. Rinse, repeat
4. Do not connect a line back up to the first point automatically, it is not clear that you have to click the first point to complete the polygon.

**Comment by z0d14c** [comment]
#649 just made a PR for this.
@mcwhittemore , or anyone else who can review + advise on anything I may have missed in the PR procedure for this project, please check this out!

**Comment by mcwhittemore** [comment]
It would be great to get some more eyes on this PR. The more people 👁 the better chance we'll catch problems.

**Comment by andrewharvey** [comment]
fixed by #649

**Comment by nicholasgonzalezsc** [comment]
@FlorianBurgevin How did you make it so that the polygon doesn't connect while being drawn?
I'd like to achieve similar behavior during drawing, but can't figure out the styling.

**Comment by FlorianBurgevin** [comment]
The gif doesn't use this library ! Sorry
