### ISSUE TITLE
immediately double clicking with polygon tool breaks the map

### ISSUE THREAD

**Issue by Briles** [mapbox/mapbox-gl-draw#680]
**mapbox-gl-js version**: v0.39.1
**mapbox-gl-draw version**: v1.0.0

### Steps to Trigger Behavior

 1. enable polygon tool
 2. immediately double click the map

### Expected Behavior

No polygon should be drawn and polygon tool should continue to work.

### Actual Behavior

No polygon is drawn, error is thrown, and polygon tool can no longer be used.

Stack trace:
```
Uncaught TypeError: Cannot read property 'toGeoJSON' of undefined
    at src\render.js:57
    at Array.map (<anonymous>)
    at module.exports.render (src\render.js:57)
    at module.exports.wrapperFn [as render] (src\lib\throttle.js:21)
    at later (src\lib\throttle.js:8)
```

#340 was a similar issue

**Comment by mcwhittemore** [comment]
Brian,

Thanks for submitting this bug report. It looks like I failed to catch some validation in the [onStop](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/modes/draw_polygon.js#L70) handler for the `draw_polygon` mode. I am not actively working on this at the time, but if you (or someone) can write a test and patch the bug I can review and merge.

Thanks,
Matthew

**Comment by AliceR** [comment]
Hi,
I think the problem is not the validation of the polygon, it is correctly identified as not valid.

For some reason, we are trying to get selected features, even if there shouldn't be be any.

`store._emitSelectionChange` should be false, when we render after changing to the simple select mode without any feature being drawn (this line: https://github.com/mapbox/mapbox-gl-draw/blob/master/src/render.js#L55).
But this should only set to true, if the option silent is false... That is why I assume that somewhere on the way our eventOption in `this.changeMode(Constants.modes.SIMPLE_SELECT, {}, { silent: true })` is ignored.

Why are the options missing in `ModeInterface.prototype.setSelected`? Changing it to 
```
ModeInterface.prototype.setSelected = function(features, options = {}) {
  return this._ctx.store.setSelected(features, options);
};
```
and also adding `{ silent: true }` to the setSelected call in the setup of the SimpleSelect seems to fix the problem, while all tests still pass. But I am not sure if this is the right solution? 

I am happy to submit a PR, but I need some help here :)

Btw, the same issue happens with draw_line when we just double click the same location.

**Comment by mcwhittemore** [comment]
@AliceR - This sounds promising, want to submit the PR so I can do a review?

**Comment by AliceR** [comment]
Another question, why is setSelected being called twice on simple_select setup? Here https://github.com/mapbox/mapbox-gl-draw/blame/master/src/modes/simple_select.js#L24 , and here https://github.com/mapbox/mapbox-gl-draw/blame/master/src/modes/simple_select.js#L28

Removing the second call has the same effect as the above suggestion. But also the same problem, I don't know how to write a test for it 😬

**Comment by mcwhittemore** [comment]
We should drop this line 

https://github.com/mapbox/mapbox-gl-draw/blame/d57440cec3a7d55055391f1941e276f1cfa24ecc/src/modes/simple_select.js#L28

**Comment by AliceR** [comment]
Thanks. I submitted a commit with tests to #687, would be great if you could have another look.
