### ISSUE TITLE
Feature request: programatic selection of feature by id

### ISSUE THREAD

**Issue by IAfanasov** [mapbox/mapbox-gl-draw#688]
Basically  my scenario is: if user placed polygon and it has some area outside of parent polygon then I need to cut placed polygon to fit parent polygon. Then I delete placed polygon and add new polygon selection is lost (this is logical). I want to select new added polygon. Think it's useful for other scenarios as well.

Same result for my scenario could be accomplished by changing a source of drown feature. I haven't found how to do it.

**Comment by mcwhittemore** [comment]
@IAfanasov,

The [Draw.add()](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md#addgeojson-object--arraystring) function lets you `add` features to Draw. If the feature you are adding has the same id as a feature currently in Draw it will overwrite this feature. Because its has the same feature id, if this feature was selected before it will still be selected.

I hope that helps. :)

Regards,
Matthew

**Comment by IAfanasov** [comment]
yep, that works! thank you
unexpected actually. method named "add" but it's behaviour is "add or update"
