### ISSUE TITLE
Trying to identify when a feature has been moved vrs modifyed

### ISSUE THREAD

**Issue by bwyss** [mapbox/mapbox-gl-draw#735]
I am trying to identify when a feature has been moved vrs modified. My overall goal it to make sure that a feature is never moved, but I do want to allow a feature's nodes to be modified.

**mapbox-gl-js version**: v0.43.0
**mapbox-gl-draw version**: v1.0.0

### Steps to Trigger Behavior

[http://jsfiddle.net/kgx2he08/2/](url)

 1. Click (hold) and drag the polygon (from the above jsfiddle) (console log shows 'change_coordinates' as the draw.update event.
 2. De-select the polygon with a single click the map (away from the polygon) 
 3. Click once more on the polygon to selected it
 4. repeat step #1, but this time the draw.update event = 'move'

### Expected Behavior
I am expecting the draw.update event to be 'moved' when the polygon is dragged, and to be 'change_coordinates' when a node is modified.

### Actual Behavior

I am getting a mix of results, described above

**Comment by mcwhittemore** [comment]
Ben,

`change_coordinates` happens when you are in `direct_select` mode and `move` happens when you are in `simple_select` mode. There is a slight change in what a feature will look like in these two modes.

Also, points can't be in direct_select mode as they have no coordinates to move.

What you are trying to do sounds like it would be best handled via a custom mode to replace `simple_select` that drops the ability to drag move.

I hope that helps,
Matthew
