### ISSUE TITLE
Delete button wont delete polygon after deleting point

### ISSUE THREAD

**Issue by rcbyrne** [mapbox/mapbox-gl-draw#739]
Hello,

When editing the polygon if you delete a point, you then can't delete the polygon unless it is deselected and then reselected. I can see this behaviour could be intentional to stop people accidentally deleting the polygon after deleting a point, however I think after deliberately reselecting the polygon I think the delete button should be reinstated.

This can be reproduced on the online demo: https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/ 

![bug](https://user-images.githubusercontent.com/964609/35631844-e6a1dab0-069c-11e8-89d2-da2cd9e55df3.gif)

mapbox-gl-js version: 0.41.0
mapbox-gl-draw version: 1.0.4

### Steps to Trigger Behavior

 1. Select Polygon Point
 2. Click "Delete" to delete point
 3. Re-select polygon
 4. Click "Delete" again and nothing happens

**Comment by mcwhittemore** [comment]
Ryan,

You are correct that this is intentional functionality. Because interface interactions are highly app dependent, we have no plans to change the default behavior. To do this yourself, you can either create a custom mode to replace `direct_select` or you can create your own UI elements that implement this logic. This is something I often do when using Draw.

Regards,
Matthew
