### ISSUE TITLE
 Bad drawing/editing performance

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-draw#89]
While you draw a polygon, the shapes are updated super-fast. But when you finish the shape and then edit it, dragging points is super-slow and laggy for some reason. I'm sure this can be fixed. cc @kelvinabrokwa

**Comment by kelvinabrokwa** [comment]
@mourner my initial thought is that this has something to do inefficient geometry translation code
https://github.com/mapbox/gl-draw/blob/master/src/util.js#L130-L173
https://github.com/mapbox/gl-draw/blob/master/src/geometries/polygon.js#L92-L107
https://github.com/mapbox/gl-draw/blob/master/src/geometries/square.js#L78-L122

to point out a few specific spots

**Comment by mourner** [comment]
@kelvinabrokwa yeah, that looks like it could be optimized, but this needs profiling to identify the specific bottleneck. I also guess that some of the slowness may be contributed by updating the textarea with GeoJSON in the editor app. If it's a bottleneck, throttling would probably help.

**Comment by kelvinabrokwa** [comment]
@mourner the performance of the example app is very similar (if not the same) to [just plain drawing on a map](https://github.com/mapbox/gl-draw/blob/master/debug/index.html) so I doubt that's much of an issue

**Comment by mourner** [comment]
Reopening because performance is currently really bad, and not just for editing but for drawing too.

I made a pure GL JS test case where a simple GeoJSON polygon is updated on mousemove and it's super-smooth, this is how it should perform in mapbox-gl-draw too: http://gfycat.com/BrownTangibleGalapagoshawk

So the bottleneck seems to be somewhere in the gl-draw code, although I can't identify it purely by profiling — this will need some trial-and-error process to figure out. Surprisingly, the `skip-worker` branch is much smoother (although editing is not fully functional there), and I don't know why it's smoother since we excluded worker transfer as the bottleneck for simple polygons. There must be some other change that affects performance in that branch.

cc @lucaswoj @mcwhittemore @kelvinabrokwa

**Comment by kelvinabrokwa** [comment]
@mourner do you mind sharing the code for your test case?

**Comment by mourner** [comment]
@kelvinabrokwa just doing setData on mousemove:

```js
map.on('mousemove', function(e) {
    var lnglat = map.unproject(e.point);
    map.getSource('geojson').setData({
        type: "Polygon",
        coordinates: [[[30.5, 50.5], [32, 50.5], [lnglat.lng, lnglat.lat], [30.5, 50.5]]]
    });
});
```

**Comment by averas** [comment]
I spent a quick ten minutes to investigate this. I put timing references in a lot of places to find any bottlenecks, but the only significant timing issue I found was the time _between_ incremental updates of the layer sources. Every event listener and subsequent render() call was within reasonable limits timing wise.

I also injected @mourner's code in various places to rule out GeoJSON-transfer/worker issues. What I immediately found was that when @mourner's code snippet was placed directly in the event handlers (such as <code>mousemove</code>) updates on the map was superfast. When I moved over the same code to the render() function things got slow, even when <code>returning</code> immediately afterwards (i.e. not running the rest of render()).

This told me that it was the actual call to the render() function that was suspicious, and yes, the render calls are wrapped in a debouncer that probably does not deliver as expected. If you simply change:

https://github.com/mapbox/mapbox-gl-draw/blob/master/src/store.js#L19

to

<code>this._render = this.render;</code>

.. things get a lot more performant. The debouncing is probably there for a reason though, so I guess the next step is to investigate why it's not working properly. And this seemingly only fixes drawing ... editing is still slow for some reason. I will put some more time into that.

**Comment by mourner** [comment]
@averas oh wow, thanks for investigating this! I wonder why it's `debounce`, it might be a mistake — in such case you usually do `throttle`, because you need to guarantee render once per 16ms, and debounce just defers the call until 16ms passed without any calls.

**Comment by averas** [comment]
@mourner Ah, yes. Might be a mistake..

As far as editing goes, I haven't found the root cause yet, however, I have strong indications that it is actually related to the dragging itself. When I short-circuit the event handlers, so that <code>mousemove</code> behaves like draggning, but without me doing so, things become performant. Simply running the render()-cycle with your code snippet (i.e. with the only thing rendered being the polygon over Ukraine) it performs great when triggered by mousemove, but get's slow when triggered by dragging, even though the rest of the code is the same.

If there is some odd interplay with mapbox-gl-js here or something else, I don't know yet..

**Comment by mourner** [comment]
@averas I just noticed that editing suddenly becomes smooth if you decrease the window width a little. At some point it suddenly starts to stutter severely. Really puzzling.

**Comment by averas** [comment]
I continued down the path of making editing possible without dragging, and as I suspected, editing became as performant as drawing (with the debouncer removed), so there is definitely something related to the act of dragging causing this. How deep down the root cause dwells remains to be answered.. but it honestly doesn't feel like this is related to mapbox-gl-draw code itself, but rather some interplay either with the browser or with mapbox-gl-js ...

**Comment by averas** [comment]
... and editing with dragging works like a charm in Safari in Firefox .. lagging is only there in Chrome.

**Comment by averas** [comment]
Just moved over to <code>master</code> on mapbox-gl-js since I saw there were some commits related to Chrome coming in lately. Now drawing and editing is snappy in all browsers! :metal:

(Still with the debouncing removed of course)

**Comment by mourner** [comment]
Awesome! :rocket: Let me get a PR with a throttle fix.

**Comment by mcwhittemore** [comment]
@mourner @kelvinabrokwa @averas thanks for pushing on this while I was away! Perf is defiantly something we need to step up for v1.0.

I'm trying to understand what the effect the changes made in the last few days to mapbox-gl-draw had on perf to help me think about perf in general, but v0.3.5 and 33d7c71c7f0c0ee50e976536fac4dd87832118fe feel almost identical to me when using v0.14.2 of mapbox-gl. Am I missing something? Here are two gifs of editing the sameish rect tangle. The alt of the images will tell you which version is which. Was the big change here moving to v0.14.2 of mapbox-gl?

![0.3.5](https://cloud.githubusercontent.com/assets/1551510/13291002/1c3338a4-dae4-11e5-9f3e-826978531df1.gif)

![33d7c71c7f0c0ee50e976536fac4dd87832118fe](https://cloud.githubusercontent.com/assets/1551510/13291003/1c3368ce-dae4-11e5-8ce7-a2411d27687a.gif)

**Comment by mcwhittemore** [comment]
Just played with dragging the rect and you can feel the difference a lot more. I think most of my testing has been moving just one vertex on a polygon, this doesn't seem wise after looking at this.

**Comment by lucaswoj** [comment]
If we're going to continue investing time improving performance in gl-draw, we _must_ write some diverse, repeatable, and quantifiable benchmarks.

**Comment by mcwhittemore** [comment]
Yea. Tests and benchmarks need to be the next push here.

**Comment by mourner** [comment]
@mcwhittemore try the master version of mapbox-gl

**Comment by mcwhittemore** [comment]
@mourner I'm seeing the same thing. To @lucaswoj point I think benchmarks are the true need here.

**Comment by mourner** [comment]
@mcwhittemore it may be not as noticeable fullscreen, but try comparing 0.3.5 and master with a small browser window. The speedup is massive, even for just dragging a vertice.

**Comment by averas** [comment]
@mcwhittemore What OS/browser are you on? Seems both me and @mourner are on OSX/Chrome.

I'm also seeing a substantial performance increase from <code>v0.3.5</code> to <code>master</code>, even when just dragging a single vertex around. If I pick a single vertex and drag it around repeatedly in a circle motion <code>v0.3.5</code> almost comes to a total freeze for me after 1-2 seconds (which makes sense considering the debouncing going on). <code>master</code> is not _perfect_ performance wise, but it's way better and does not degrade as I move around repeatedly.

**Comment by mcwhittemore** [comment]
@averas - @mourner pointed out that what I'm seeing is because of screen size. When dragging one vertex around on a full screen map the two versions are more or less the same, but when shrinking the size of the screen the master branch improves a bunch and the v0.3.5 does not.

**Comment by averas** [comment]
@mcwhittemore Ah, alright. That effect can probably be explained by the fact that at some point when increasing the window size the performance limitations of mapbox-gl-js "takes over" and becomes the limiting factor rather than draw. As you can see from my posts above I did quite substantial testing last week to isolate any bottlenecks in draw and the debounced render-call was the only obvious one (aside from the dragging effects present in Chrome). To reach this conclusion I had code injected in lots of places to compare "drawing" with just transferring GeoJSON via the callbacks. 

From this point I think there are two main factors that can increase draw performance substantially:

1. Increase rendering performance of poly-fills in mapbox-gl-js (try out draw with a rebased <code>earcut-final</code>)
2. Increase the performance of the setData-call, by any or several of the means discussed in various threads here and over at mapbox-gl-js

**Comment by mcwhittemore** [comment]
Sounds good! Thanks for digging into this so much, its greatly appreciated.

**Comment by AliFlux** [comment]
Hey guys, any update on this issue?
