### ISSUE TITLE
Warning about use of unsupported package

### ISSUE THREAD

**Issue by daveisfera** [mapbox/mapbox-gl-draw#895]
**mapbox-gl-js version**: 1.0.0
**mapbox-gl-draw version**: 1.1.2

### Steps to Trigger Behavior
 1. Add `@mapbox/mapbox-gl-draw` to `package.json`
 2. Run `yarn install`

### Expected Behavior
Installs without errors

### Actual Behavior
Give the following warning:
`@mapbox/mapbox-gl-draw > @mapbox/geojsonhint > jsonlint-lines > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.`

**Comment by raysuelzer** [comment]
They should not be using this package. It is not meant for browser code, is not maintained, and breaks angular and vue apps. 

Maybe I will try and put in a PR to remove it.

**Comment by ansis** [comment]
Thanks for opening this issue. There are things we can do to eliminate this warning, but in the mean time, there are no actual errors caused by this. It should be safe to ignore it for now

The geojsonhint dependency of this project uses a fork of jsonlint which depends on nomnom. We need to switch to a different fork of jsonlint but need to check that the other fork works for geojsonhint. After a quick look like it does but I need to review the test differences more carefully to be sure. We’ll keep this ticket updated

**Comment by daveisfera** [comment]
My hope is that I don't need to use unmaintained code to use Mapbox, so I'm not looking eliminate the warning but to make sure that Mapbox will continue working and not end up with unpatched security vulnerabilities in the future.

**Comment by kkaefer** [comment]
This is fixed in current master, waiting for a release.

**Comment by daveisfera** [comment]
Any ETA on when we can expect the release?

**Comment by kkaefer** [comment]
I released a 1.2.0 beta version today: https://github.com/mapbox/mapbox-gl-draw/releases/tag/v1.2.0-beta.1; it's also on NPM. Check it out!

**Comment by daveisfera** [comment]
I just tested it out and shouldn't `eslint-plugin-import` be in `devDependencies`? It's not actually used by the module is it and isn't needed in `dependencies`?

**Comment by daveisfera** [comment]
@kkaefer any update on this?

**Comment by asheemmamoowala** [comment]
@daveisfera I think you're right. The `eslint-plugin-import` dependency should be listed under `devDependencies`. Want to contribute a PR?

**Comment by daveisfera** [comment]
https://github.com/mapbox/mapbox-gl-draw/pull/955
