### ISSUE TITLE
Latest release v1.1.2 is not available via CDN

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-draw#914]
The latest via CDN available release is `v1.0.9`:

https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.0.9/mapbox-gl-draw.js
https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.0.9/mapbox-gl-draw.css

**Comment by andrewharvey** [comment]
Looks like this is now working.

**Comment by kkaefer** [comment]
Thanks for the report; our current deploy process for this module is broken, so releases weren't automatically published to S3. They are, however, available in npm. I manually published them to our CDN, so 1.1.0, 1.1.1, and 1.1.2 should now be available.

I'm also working on fixing our automatic deployment process so that future releases will be deployed correctly.
