### ISSUE TITLE
Map is not movable when simple_select is modified  and dragMove of feature is disabled 

### ISSUE THREAD

**Issue by crow7m** [mapbox/mapbox-gl-draw#935]
When disabling feature selection, (Polygon);

        `const NewSimpleSelect = _.extend(MapboxDraw.modes.simple_select, {
        dragMove(e) {
        console.log("dragMove") //don't do anything cause want to prevent Polygon movement.
        },

      });
    
      const drawControl = new MapboxDraw({
        modes: {
          ...MapboxDraw.modes,
          simple_select: NewSimpleSelect,
          direct_select: NewDirectSelect,
        }})`
However when clicking on polygon and trying to move(drag) the map below it, map is not moving as well.

Expected Behavior:********** 
 when  drag of polygon is disabled, map still should be movable(draggable)

Actual Behavior: When Polygon simple_select dragMove is modified and tryng to move the map below polygon, map is not moving 

Thank you for your help

**Comment by fc** [comment]
You will find this useful:
https://github.com/mapbox/mapbox-gl-draw-static-mode

> This is a custom mode for @mapbox/mapbox-gl-draw that displays data stored in Draw but does not let the user interact with it.

Essentially: It will disable selection of any of the polygons, yet the map will move if you drag it.

You may also want to override the static style since it is more of a black color:
https://github.com/mapbox/mapbox-gl-draw/blob/master/src/lib/theme.js

Specifically these styles: `gl-draw-polygon-fill-static`, `gl-draw-polygon-stroke-static`, `gl-draw-line-static`, and `gl-draw-point-static`.

**Comment by crow7m** [comment]
> You will find this useful:
> https://github.com/mapbox/mapbox-gl-draw-static-mode
> 
> > This is a custom mode for @mapbox/mapbox-gl-draw that displays data stored in Draw but does not let the user interact with it.
> 
> Essentially: It will disable selection of any of the polygons, yet the map will move if you drag it.
> 
> You may also want to override the static style since it is more of a black color:
> https://github.com/mapbox/mapbox-gl-draw/blob/master/src/lib/theme.js
> 
> Specifically these styles: `gl-draw-polygon-fill-static`, `gl-draw-polygon-stroke-static`, `gl-draw-line-static`, and `gl-draw-point-static`.

thank you i will check his out
