### ISSUE TITLE
move API.md into README.md

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/mapbox-gl-draw#95]
don't need a separate document that is honestly somewhat hard to fine

**Comment by tristen** [comment]
Dunno. Using something like [documentationjs](https://github.com/documentationjs/documentation) and writing out to a API.md file is pretty nice. See: https://github.com/mapbox/mapbox-sdk-js/blob/2fe5499d4229fca6b633fb64008a2909219d9681/package.json#L12. And why not just make the link to API big and bold in the README?

**Comment by kelvinabrokwa** [comment]
@tristen unfortuately documentationjs doesn't quite support ES6.

And making the link big is also an options.

**Comment by mh166** [comment]
I just found this repo some minutes ago. But since the Readme.md is very short, it was no prob to figure out, where I have to look at. :+1: 

So even as a new user, it totally makes sense. The only thing I can think of, is to change the wording to something like `See API.md for complete reference.` or so. Because to me, it's not only "advanced usage" but really it is essential to know what's there and how to use it. :wink:
