### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAll' of null 

### ISSUE THREAD

**Issue by Zheniss** [mapbox/mapbox-gl-draw#957]
**mapbox-gl-js version**:
**mapbox-gl-draw version**:

### Steps to Trigger Behavior

 1. Get control instance 
 2. Add control to the map
 3. Remove control
 4. Add control again
 5. Call getAll() method of control

This is because of assign null to ctx.store

https://github.com/mapbox/mapbox-gl-draw/blob/c7ff98dfc92aa2befb46bb212e7b59ce7bb89820/src/setup.js#L25

```typescript
      const control = new MapboxDraw({
        displayControlsDefault: false,
        controls: {
          polygon: true,
          trash: true
        },
        userProperties: true,
        styles: drawStyles
      });

      mapInstance.addControl(control);
      mapInstance.removeControl(control);
      mapInstance.addControl(control);

      const { features } = control.getAll();

      // Features array
      console.log('features: ', features);

```

### Expected Behavior
   Features array

### Actual Behavior
```typescript
     
      zone-evergreen.js:172 Uncaught TypeError: Cannot read property 'getAll' of null
    at push../node_modules/@mapbox/mapbox-gl-draw/index.js.module.exports.api.getAll (api.js:121)
```

**Comment by Zheniss** [comment]
I just get a new instance of control.

**Comment by carefulAxe** [comment]
Also experiencing this exact issue. Any way to safely remove controls from a map?

**Comment by jamalnoroze** [comment]
Also experiencing this exact issue. Any solution?

**Comment by carefulAxe** [comment]
We ended up invoking getAll on the draw control within a pipe tap (ngrx) and somehow we no longer have the issue.

**Comment by l0rn** [comment]
Also experiencing this - could this please be reopened as it is perfectly reproducible with mapbox-gl-draw 1.3.0

**Comment by brambow** [comment]
Same issue here as well

**Comment by wtravO** [comment]
Bump. Anyone found a solution for this?

**Comment by annabushsoftware** [comment]
I encountered this issue but discovered that it was due to neglecting to remove the event listeners related to MapboxDraw when I removed the control. Then when I added a new MapboxDraw control (and associated event listener), it caused the event listener to be called twice: once for a MapboxDraw control that no longer existed on the map (breaks), and once for the new, unbroken control. 

Before (caused "Cannot read property 'getAll' of null" bug): 
`
const addControlToMap = () => {
  mapInstance.addControl(mapboxDrawControl, 'top-left')
  mapInstance.on('draw.create', onDrawCreate)
}
` 
...
`
const removeControlFromMap = () => {
  mapInstance.removeControl(mapboxDrawControl)
}
`

After: 
...
`
const removeControlFromMap = () => {
  mapInstance.off('draw.create', onDrawCreate)
  mapInstance.removeControl(mapboxDrawControl)
}
`

Versions:
Vue 3.2.36
`
"@mapbox/mapbox-gl-draw": "^1.4.1",
"mapbox-gl": "^2.10.0",
`

**Comment by niaoshanming** [comment]
> I encountered this issue but discovered that it was due to neglecting to remove the event listeners related to MapboxDraw when I removed the control. Then when I added a new MapboxDraw control (and associated event listener), it caused the event listener to be called twice: once for a MapboxDraw control that no longer existed on the map (breaks), and once for the new, unbroken control.
> 
> Before (caused "Cannot read property 'getAll' of null" bug):
> 
> ```
> const addControlToMap = () => {
>   mapInstance.addControl(mapboxDrawControl, 'top-left')
>   mapInstance.on('draw.create', onDrawCreate)
> }
> ```
> 
> ...
> 
> ```
> const removeControlFromMap = () => {
>   mapInstance.removeControl(mapboxDrawControl)
> }
> ```
> 
> After: ...
> 
> ```
> const removeControlFromMap = () => {
>   mapInstance.off('draw.create', onDrawCreate)
>   mapInstance.removeControl(mapboxDrawControl)
> }
> ```
> 
> Versions: Vue 3.2.36
> 
> ```
> "@mapbox/mapbox-gl-draw": "^1.4.1",
> "mapbox-gl": "^2.10.0",
> ```

6666666
