### ISSUE TITLE
Render drawing tool on top of tiles?

### ISSUE THREAD

**Issue by jayarjo** [mapbox/mapbox-gl-draw#992]
Not sure if this a right place to ask, but not sure where else to ask.

Is there a style/option that controls zIndex of drawing tools in regards to other layers, like tiles? In our case drawing tools gets rendered underneath vector tiles.

**Comment by Zirak** [comment]
mapbox-draw is appended to the layers list, so one way is to load mapbox-draw _after_ loading other layers.

Of course, that's not a very good answer ;) So instead you might be interested in [`map.moveLayer`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#movelayer) to move the mapbox-draw layers around.

**Comment by jayarjo** [comment]
@Zirak from what I see drawing tools can be appended either immediately or after a delay. In our cases that causes them to be inserted not were they are expected. I solved it on our end now, however would be great if drawing tools as a whole accepted something like `beforeId`, similar to  how `map.addLayer` accepts.

**Comment by adrianababakanian** [comment]
> I solved it on our end now, however would be great if drawing tools respected something like beforeId, similar to how map.addLayer does.

@jayarjo it sounds like the discussion in this PR https://github.com/mapbox/mapbox-gl-draw/pull/983 is similar to what you are looking for. Is that correct? Or by "drawing tools," do you mean the DOM elements representing the controls rather than the map layers added by GL Draw?

[`Map#addControl`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addcontrol) does not add a layer to the map itself, but rather a DOM node with a class of `'mapboxgl-ctrl-group'`, so it is not expected that the the controls representing the "drawing tools" would be inserted between layers of the map depending on when Draw is loaded. Could you share a reproducible example if this is the case?

Otherwise, if you are looking to control the ordering of the layers added to the map by GL Draw, the [`Map#moveLayer` ](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#movelayer)method is likely a cleaner approach than introducing a `beforeId` to Draw's `options` (as discussed in the PR linked above).
